name: First-Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Welcome to BMW"
      - name: Print Send Off Message
        run: echo "Good bye! Have a nice day."
